### ISSUE TITLE
corrupted io.jxcore.node.jx plugin 

### ISSUE THREAD

**Issue by Santosh-Goswami** [jxcore/jxcore-cordova#117] opened 2016-01-01 07:09 UTC
Hi , 
I was download  io.jxcore.node.jx plugin from :- " https://github.com/jxcore/jxcore-cordova-release/raw/master/0.0.8/io.jxcore.node.jx"   (size-89mb  \ 93,333,348 bytes)
After that when I used this plugin with following command on Ubuntu system:-
(Note:- jxcore was already install on my system)
jx io.jxcore.node.jx
it gives an error-
Package is corrupted /home/ubuntu/workspace/io.jxcore.node.jx
I also try 0.0.4, 0.0.5, 0.0.7 plugins but got same error.
so please help me.

**Comment by ktrzeciaknubisa** [comment] 2016-01-02 11:38
I've checked on both Ubuntu x64 and x32. I used the newest JXcore 0.3.1.0 and previous 0.3.0.7. I didn't find any problem.

Which exactly Ubuntu is this? And which jxcore:

``` bash
$ jx -jxv && jx -jsv && jx -a
```

The file size you show is correct, let's also check the sha256 sum. Please execute the following:

``` bash
$ echo "0ae5151e016d2fe6b8d1d37fcf78e09702ebc1d95434d285ddf0568478501b69  io.jxcore.node.jx" > shafile.txt 
$ shasum -a 256 -c shafile.txt 
$ rm -f shafile.txt
```

It should output:

``` bash
io.jxcore.node.jx: OK
```

**Comment by ktrzeciaknubisa** [comment] 2016-01-14 12:06
We cannot reproduce this and the packages were double checked. I'm closing.

@Santosh-Goswami feel free to reopen if you have some more details. Also we recommend to use [jxc](https://github.com/jxcore/jxc) for downloading/installing the plugin. It has been improved recently for http error handling.

**Closed as completed by ktrzeciaknubisa** 2016-01-14 12:06 UTC
