### ISSUE TITLE
js_ReportOverRecursed called

### ISSUE THREAD

**Issue by oriharel** [jxcore/jxcore-cordova#35] opened 2015-06-14 05:40 UTC
I looked at the jxcore-cordova plugin, and I was very interested in it, especially the part where it registers JavaScript functions and call them from Java code.

I tried to follow the footsteps of the sample, and also registered JavaScript function using my own defineEventCB function (I copied it from the plugin). Then I call callCBString from Java, but I get:

06-14 00:38:37.863 989-1002/? W/jxcore-log﹕ !!! js_ReportOverRecursed called !!!

The thing is, I call defineEventCB from thread 1, but callCBString from thread 2 (I can't control the threads creations. it a system generated flow).

If I call these 2 functions from the same thread, everything works fine. Any idea how to do this?

Thanks, 
Ori

**Comment by obastemur** [comment] 2015-06-15 11:23
closing this one (duplicate of https://github.com/jxcore/jxcore/issues/395)

**Closed as completed by obastemur** 2015-06-15 11:23 UTC
